In [1]:
import numpy as np

## Data types && Attributes

In [2]:
# numpy main data type is ndarray
mylist = np.array([1,2,3,4,5])
mylist

array([1, 2, 3, 4, 5])

In [3]:
type(mylist)

numpy.ndarray

In [4]:
# 3 column and 1 row
# Names: vector , Array
# 1 dimensional
# Shape (1,3)
T1 = np.array([1,2,3])
T1

array([1, 2, 3])

In [5]:
# 3 column and 2 row
# Names: Matrix , Array
# More than 1 dimension
# Shape (2,3)
T2 = np.array([
        [1,2,3],
        [4,5,6]])
T2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# x column and x row with x axis
# Names: Matrix , Array
# More than 1 dimension
# Shape (2,3,3)
T3 = np.array([[
                [1,2,3],
                [4,5,6],
                [7,8,9]],
                [
                [10,11,12],
                [13,14,15],
                [16,17,18]
              ]])
T3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# shape attribute
T3.shape

(2, 3, 3)

In [8]:
T1.ndim, T2.ndim, T3.ndim

(1, 2, 3)

In [9]:
T1.size, T2.size, T3.size

(3, 6, 18)

## manipulating arrays and comparing arrays

#### Arithmetic

In [10]:
np.ones(4) + np.array([1,2,3,4])

array([2., 3., 4., 5.])

In [11]:
np.ones(4) - np.array([1,2,3,4])

array([ 0., -1., -2., -3.])

In [12]:
np.ones(4) * np.array([1,2,3,4])

array([1., 2., 3., 4.])

#### Aggregation

In [13]:
# aggregation performing the same operation on a number of things
listy_list = np.array([1, 2, 3])
np.sum(listy_list)

6

note:
Use Python methods (`sum()`) on Python datatypes and use NumPy's methods on 
Numpy array (`np.sum()`)

In [14]:
# create massive array with numpy
massive_array = np.random.random(99999)
massive_array[:10]

array([0.77108993, 0.86283902, 0.77089404, 0.87105333, 0.97483176,
       0.78255242, 0.26921807, 0.95748192, 0.84966281, 0.40030469])

In [15]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

12.2 ms ± 231 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35 µs ± 739 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
# deviation && variance
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [17]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

#### reshaping and transposing

In [29]:
not_shaped = np.array([
    [1,3,5],
    [4,5,9]
])
not_shaped.shape
# now the reshaped
not_shaped.reshape(2,3,1).shape

(2, 3, 1)

## Dot product

In [44]:
d1 = np.random.randint(10, size=(3,3))
d2 = np.random.randint(10, size=(3,2))
# now if we dot the arrays
# the shape should be external numbers
# mean 3 x 2
print(np.dot(d1, d2))
# or we can simply swap and flipit
# to get our target shape that we need
print(np.dot(d1, d1.T))

[[10  4]
 [28 22]
 [34 22]]
[[ 40  28   8]
 [ 28 101  71]
 [  8  71  65]]
