In [1]:
import numpy as np

## Data types && Attributes

In [2]:
# numpy main data type is ndarray
mylist = np.array([1,2,3,4,5])
mylist

array([1, 2, 3, 4, 5])

In [3]:
type(mylist)

numpy.ndarray

In [4]:
# 3 column and 1 row
# Names: vector , Array
# 1 dimensional
# Shape (1,3)
T1 = np.array([1,2,3])
T1

array([1, 2, 3])

In [6]:
# 3 column and 2 row
# Names: Matrix , Array
# More than 1 dimension
# Shape (2,3)
T2 = np.array([
        [1,2,3],
        [4,5,6]])
T2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# x column and x row with x axis
# Names: Matrix , Array
# More than 1 dimension
# Shape (2,3,3)
T3 = np.array([[
                [1,2,3],
                [4,5,6],
                [7,8,9]],
                [
                [10,11,12],
                [13,14,15],
                [16,17,18]
              ]])
T3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
# shape attribute
T3.shape

(2, 3, 3)

In [15]:
T1.ndim, T2.ndim, T3.ndim

(1, 2, 3)

In [16]:
T1.size, T2.size, T3.size

(3, 6, 18)